blank_issues_enabled: false
contact_links:
  - name: Projekt-Dokumentation
    url: https://github.com/methmx83/OC_F-Studio/tree/main/DOKUMENTATIONEN
    about: Vor neuen Issues zuerst in bestehende Dokumentation schauen.
