export const IPC_CHANNELS = {
  project: {
    new: 'project:new',
    save: 'project:save',
    load: 'project:load',
    getRoot: 'project:get-root',
    listWorkflowCatalog: 'project:list-workflow-catalog',
    importVideo: 'project:import-video',
    importImage: 'project:import-image',
    importAudio: 'project:import-audio',
    importComfyOutput: 'project:import-comfy-output',
    listComfyGallery: 'project:list-comfy-gallery',
    savePreviewSnapshot: 'project:save-preview-snapshot',
    importWorkflowTemplate: 'project:import-workflow-template',
    getWorkflowPresets: 'project:get-workflow-presets',
    saveWorkflowPresets: 'project:save-workflow-presets',
    assetThumbnailDataUrl: 'project:asset-thumbnail-data-url',
    assetFileUrl: 'project:asset-file-url',
    assetMediaDataUrl: 'project:asset-media-data-url',
    ffmpegHealth: 'project:ffmpeg-health',
    ensureVideoProxy: 'project:ensure-video-proxy',
    audioWaveformPeaks: 'project:audio-waveform-peaks',
  },
  comfy: {
    health: 'comfy:health',
    queueRun: 'comfy:queue-run',
    previewRun: 'comfy:preview-run',
    cancelRun: 'comfy:cancel-run',
    runEvent: 'comfy:run-event',
  },
} as const;

