import type { StudioState } from '../studioStore';

export const selectTimelineDockStoreState = (state: StudioState) => ({
  timeline: state.timeline,
  assets: state.assets,
  droppedAssetIds: state.droppedAssetIds,
  selectedClip: state.selectedClip,
  lastError: state.lastError,
  currentTime: state.currentTime,
  setCurrentTime: state.setCurrentTime,
  addTrack: state.addTrack,
  dropAssetToTimeline: state.dropAssetToTimeline,
  timelineAddClip: state.timelineAddClip,
  selectClip: state.selectClip,
  clearClipSelection: state.clearClipSelection,
  nudgeSelectedClip: state.nudgeSelectedClip,
  trimSelectedClip: state.trimSelectedClip,
  slipSelectedClip: state.slipSelectedClip,
  setSelectedClipGain: state.setSelectedClipGain,
  setSelectedClipGainAutomation: state.setSelectedClipGainAutomation,
  cutSelectedClipAtCurrentTime: state.cutSelectedClipAtCurrentTime,
  removeSelectedClip: state.removeSelectedClip,
  rippleRemoveSelectedClip: state.rippleRemoveSelectedClip,
  timelineMoveClip: state.timelineMoveClip,
  timelineTrimClip: state.timelineTrimClip,
  trackAudioMutedById: state.trackAudioMutedById,
  trackAudioSoloById: state.trackAudioSoloById,
  toggleTrackAudioMute: state.toggleTrackAudioMute,
  toggleTrackAudioSolo: state.toggleTrackAudioSolo,
  clearTrackAudioMixStates: state.clearTrackAudioMixStates,
});
